import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { copyFileSync, existsSync, mkdirSync, readdirSync, statSync } from 'node:fs'
import { resolve } from 'node:path'
import { getPool } from './db'

const pExec = promisify(execFile)

export interface Migration {
  version: number
  name: string
  sql: string[]
}

export interface MigrationRecord {
  version: number
  name: string
  applied_at: number
  note: string | null
}

function qualifiedTable(name: string): string {
  if (name.startsWith('players.')) {
    const t = name.slice('players.'.length)
    return `players.${t}`
  }
  if (name.startsWith('_meta.')) {
    const t = name.slice('_meta.'.length)
    return `_meta.${t}`
  }
  if (name === '_migrations') return '_meta._migrations'
  return `world.${name}`
}

function rewriteSql(sql: string): string {
  return sql
    .replace(/\b_migrations\b/g, '_meta._migrations')
    .replace(/\bplayers\.player_/g, 'players.player_')
    .replace(/\bplayers\._/g, 'players._')
    .replace(/\bCREATE TABLE IF NOT EXISTS\s+world_/g, 'CREATE TABLE IF NOT EXISTS world.world_')
    .replace(/\bCREATE TABLE IF NOT EXISTS\s+player_/g, 'CREATE TABLE IF NOT EXISTS players.player_')
    .replace(/\bALTER TABLE\s+world_/g, 'ALTER TABLE world.world_')
    .replace(/\bALTER TABLE\s+player_/g, 'ALTER TABLE players.player_')
    .replace(/\bUPDATE\s+world_/g, 'UPDATE world.world_')
    .replace(/\bUPDATE\s+player_/g, 'UPDATE players.player_')
    .replace(/\bDROP COLUMN\s+pattern\b/g, 'DROP COLUMN pattern')
    .replace(/PRIMARY KEY AUTOINCREMENT/g, 'GENERATED BY DEFAULT AS IDENTITY')
    .replace(/AUTOINCREMENT/g, 'GENERATED BY DEFAULT AS IDENTITY')
}

const MIGRATIONS: Migration[] = [
  {
    version: 1,
    name: 'add_dialogue_root_to_world_mobs',
    sql: ['ALTER TABLE world.world_mobs ADD COLUMN dialogue_root TEXT;'],
  },
  {
    version: 2,
    name: 'create_world_quests',
    sql: [
      `CREATE TABLE IF NOT EXISTS world.world_quests (
        world_id TEXT NOT NULL,
        quest_id TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        script_ref TEXT,
        PRIMARY KEY (world_id, quest_id)
      );`,
    ],
  },
  {
    version: 3,
    name: 'create_world_quest_objectives',
    sql: [
      `CREATE TABLE IF NOT EXISTS world.world_quest_objectives (
        world_id TEXT NOT NULL,
        quest_id TEXT NOT NULL,
        ordinal INTEGER NOT NULL,
        kind TEXT NOT NULL,
        target TEXT,
        count INTEGER DEFAULT 1,
        PRIMARY KEY (world_id, quest_id, ordinal)
      );`,
    ],
  },
  {
    version: 4,
    name: 'create_world_quest_rewards',
    sql: [
      `CREATE TABLE IF NOT EXISTS world.world_quest_rewards (
        world_id TEXT NOT NULL,
        quest_id TEXT NOT NULL,
        ordinal INTEGER NOT NULL,
        kind TEXT NOT NULL,
        payload_json TEXT,
        PRIMARY KEY (world_id, quest_id, ordinal)
      );`,
    ],
  },
  {
    version: 5,
    name: 'add_symbol_width_to_world_worlds',
    sql: ['ALTER TABLE world.world_worlds ADD COLUMN symbol_width INTEGER DEFAULT 1;'],
  },
  {
    version: 6,
    name: 'migrate_floor_settings_overrides',
    sql: [
      "ALTER TABLE world.world_regions ADD COLUMN floor_settings_deprecated_at INTEGER;",
    ],
  },
  {
    version: 7,
    name: 'create_migrations_table_marker',
    sql: [
      `CREATE TABLE IF NOT EXISTS _meta._migrations (
        version INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        applied_at BIGINT NOT NULL,
        note TEXT
      );`,
    ],
  },
  {
    version: 8,
    name: 'add_pattern_to_world_terrains',
    sql: [
      "ALTER TABLE world.world_terrains ADD COLUMN pattern TEXT DEFAULT 'none';",
    ],
  },
  {
    version: 9,
    name: 'auto_assign_patterns_to_default_tiles',
    sql: [
      "UPDATE world.world_terrains SET pattern = 'hatch'   WHERE symbol = 'x';",
      "UPDATE world.world_terrains SET pattern = 'dots'    WHERE symbol = '~';",
      "UPDATE world.world_terrains SET pattern = 'stripes' WHERE symbol = 'T';",
      "UPDATE world.world_terrains SET pattern = 'none'    WHERE symbol = '.';",
    ],
  },
  {
    version: 10,
    name: 'drop_pattern_column_from_world_terrains',
    sql: [
      'ALTER TABLE world.world_terrains DROP COLUMN pattern;',
    ],
  },
  {
    version: 11,
    name: 'add_region_metadata',
    sql: [
      "ALTER TABLE world.world_regions ADD COLUMN region_kind TEXT DEFAULT 'static';",
      'ALTER TABLE world.world_regions ADD COLUMN generator_script TEXT;',
      'ALTER TABLE world.world_regions ADD COLUMN template_config_json TEXT;',
      'ALTER TABLE world.world_regions ADD COLUMN tutorial_steps_json TEXT;',
    ],
  },
  {
    version: 12,
    name: 'create_world_recipes',
    sql: [
      `CREATE TABLE IF NOT EXISTS world.world_recipes (
        world_id TEXT NOT NULL,
        recipe_id TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        skill_id TEXT,
        required_skill_level INTEGER DEFAULT 0,
        station_type TEXT,
        outputs_json TEXT,
        inputs_json TEXT,
        craft_time_seconds REAL DEFAULT 3.0,
        experience_gain INTEGER DEFAULT 0,
        script_ref TEXT,
        is_auto_learned INTEGER DEFAULT 1,
        PRIMARY KEY (world_id, recipe_id)
      );`,
    ],
  },
  {
    version: 13,
    name: 'create_player_known_recipes',
    sql: [
      `CREATE TABLE IF NOT EXISTS players.player_known_recipes (
        uid INTEGER NOT NULL,
        world_id TEXT NOT NULL,
        recipe_id TEXT NOT NULL,
        learned_at BIGINT NOT NULL,
        PRIMARY KEY (uid, world_id, recipe_id)
      );`,
    ],
  },
  {
    version: 14,
    name: 'add_xp_curve_to_world_skills',
    sql: [
      "ALTER TABLE world.world_skills ADD COLUMN xp_curve TEXT DEFAULT 'linear';",
      'ALTER TABLE world.world_skills ADD COLUMN xp_curve_params TEXT;',
    ],
  },
  {
    version: 15,
    name: 'add_station_type_to_world_interactables',
    sql: [
      'ALTER TABLE world.world_interactables ADD COLUMN station_type TEXT;',
    ],
  },
  {
    version: 16,
    name: 'drop_world_worlds_and_world_id_columns',
    sql: [
      `DO $$
       DECLARE r record;
       BEGIN
         FOR r IN
           SELECT n.nspname AS schema, c.relname AS table_name, con.conname AS fk_name
             FROM pg_constraint con
             JOIN pg_class c ON c.oid = con.conrelid
             JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE con.contype = 'f'
              AND n.nspname IN ('world', 'players')
              AND EXISTS (
                SELECT 1 FROM unnest(con.conkey) k
                  JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = k
                 WHERE a.attname = 'world_id'
              )
         LOOP
           EXECUTE format('ALTER TABLE %I.%I DROP CONSTRAINT %I', r.schema, r.table_name, r.fk_name);
         END LOOP;
       END$$;`,
      `DO $$
       DECLARE r record;
       BEGIN
         FOR r IN
           SELECT n.nspname AS schema, c.relname AS table_name, con.conname AS pk_name
             FROM pg_constraint con
             JOIN pg_class c ON c.oid = con.conrelid
             JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE con.contype = 'p'
              AND n.nspname IN ('world', 'players')
              AND EXISTS (
                SELECT 1 FROM unnest(con.conkey) k
                  JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = k
                 WHERE a.attname = 'world_id'
              )
         LOOP
           EXECUTE format('ALTER TABLE %I.%I DROP CONSTRAINT %I', r.schema, r.table_name, r.pk_name);
         END LOOP;
       END$$;`,
      `DO $$
       DECLARE r record;
       BEGIN
         FOR r IN
           SELECT n.nspname AS schema, c.relname AS table_name, i.indexrelid::regclass AS idx_name
             FROM pg_index i
             JOIN pg_class c ON c.oid = i.indrelid
             JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname IN ('world', 'players')
              AND NOT i.indisprimary
              AND NOT i.indisunique
              AND EXISTS (
                SELECT 1 FROM unnest(i.indkey) k
                  JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = k
                 WHERE a.attname = 'world_id'
              )
         LOOP
           EXECUTE format('DROP INDEX IF EXISTS %I.%I', r.schema, r.idx_name);
         END LOOP;
       END$$;`,
      `DO $$
       DECLARE r record;
       BEGIN
         FOR r IN
           SELECT n.nspname AS schema, c.relname AS table_name, con.conname AS uq_name
             FROM pg_constraint con
             JOIN pg_class c ON c.oid = con.conrelid
             JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE con.contype = 'u'
              AND n.nspname IN ('world', 'players')
              AND EXISTS (
                SELECT 1 FROM unnest(con.conkey) k
                  JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = k
                 WHERE a.attname = 'world_id'
              )
         LOOP
           EXECUTE format('ALTER TABLE %I.%I DROP CONSTRAINT %I', r.schema, r.table_name, r.uq_name);
         END LOOP;
       END$$;`,
      'DROP TABLE IF EXISTS world.world_worlds CASCADE;',
      'ALTER TABLE world.world_regions            DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_rooms              DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_room_exits         DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_room_spawns        DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_terrains           DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_items              DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_mobs               DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_interactables      DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_loot_tables        DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_skill_categories   DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_skills             DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_dialogues          DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_quests             DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_quest_objectives   DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_quest_rewards      DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_recipes            DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_region_overrides   DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE world.world_field_definitions  DROP COLUMN IF EXISTS world_id;',
      'ALTER TABLE players.player_known_recipes   DROP COLUMN IF EXISTS world_id;',
    ],
  },
  {
    version: 17,
    name: 'add_floor_columns_and_palette_to_world_regions',
    sql: [
      'ALTER TABLE world.world_regions ADD COLUMN IF NOT EXISTS floor_tribe TEXT;',
      'ALTER TABLE world.world_regions ADD COLUMN IF NOT EXISTS floor_index INT;',
      'ALTER TABLE world.world_regions ADD COLUMN IF NOT EXISTS floor_meta  INT;',
      'ALTER TABLE world.world_regions ADD COLUMN IF NOT EXISTS biome_theme TEXT;',
      'ALTER TABLE world.world_regions ADD COLUMN IF NOT EXISTS floor_palette_json TEXT;',
    ],
  },
    {
    version: 18,
    name: 'add_region_metadata',
    sql: [
      "ALTER TABLE world.world_regions DROP COLUMN region_kind TEXT DEFAULT 'static';",
      'ALTER TABLE world.world_regions DROP COLUMN generator_script TEXT;',
      'ALTER TABLE world.world_regions DROP COLUMN template_config_json TEXT;',
      'ALTER TABLE world.world_regions DROP COLUMN tutorial_steps_json TEXT;',
    ],
  },
  {
    version: 19,
    name: 'add_room_light_and_exit_one_way',
    sql: [
      "ALTER TABLE world.world_rooms ADD COLUMN IF NOT EXISTS light INT NOT NULL DEFAULT 0;",
      "COMMENT ON COLUMN world.world_rooms.light IS '0 = dark, 10 = bright';",
    ],
  },
  {
    version: 20,
    name: 'create_factions',
    sql: [
      `CREATE TABLE IF NOT EXISTS world.world_factions (
        faction_id TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        ideology TEXT,
        PRIMARY KEY (faction_id)
      );`,
      `CREATE TABLE IF NOT EXISTS world.world_faction_relations (
        faction_id TEXT NOT NULL,
        other_faction_id TEXT NOT NULL,
        base_standing INT NOT NULL DEFAULT 0,
        PRIMARY KEY (faction_id, other_faction_id)
      );`,
      `CREATE TABLE IF NOT EXISTS players.player_faction_standing (
        player_id INT NOT NULL,
        faction_id TEXT NOT NULL,
        standing INT NOT NULL DEFAULT 0,
        updated_at BIGINT NOT NULL,
        PRIMARY KEY (player_id, faction_id)
      );`,
    ],
  },
  {
    version: 21,
    name: 'create_player_gold_and_shops',
    sql: [
      "ALTER TABLE players.player_players ADD COLUMN IF NOT EXISTS gold INT NOT NULL DEFAULT 0;",
      "ALTER TABLE players.player_players ADD COLUMN IF NOT EXISTS bank_balance INT NOT NULL DEFAULT 0;",
      `CREATE TABLE IF NOT EXISTS world.world_shop_keeper (
        keeper_id TEXT NOT NULL,
        mob_id TEXT,
        markup NUMERIC NOT NULL DEFAULT 1.0,
        markdown NUMERIC NOT NULL DEFAULT 1.0,
        open_hour INT DEFAULT 0,
        close_hour INT DEFAULT 24,
        shop_type TEXT DEFAULT 'general',
        PRIMARY KEY (keeper_id)
      );`,
      `CREATE TABLE IF NOT EXISTS world.world_shop_inventory (
        keeper_id TEXT NOT NULL,
        template_id TEXT NOT NULL,
        max_stock INT NOT NULL DEFAULT -1,
        restock_seconds INT NOT NULL DEFAULT 600,
        current_stock INT NOT NULL DEFAULT -1,
        price_override INT,
        PRIMARY KEY (keeper_id, template_id)
      );`,
    ],
  },
  {
    version: 22,
    name: 'create_mail_and_boards',
    sql: [
      `CREATE TABLE IF NOT EXISTS players.player_mail (
          mail_id BIGSERIAL PRIMARY KEY,
          from_player_id INT NOT NULL,
          to_player_id INT NOT NULL,
          subject TEXT NOT NULL,
          body TEXT NOT NULL,
          sent_at BIGINT NOT NULL,
          read_at BIGINT,
          folder TEXT NOT NULL DEFAULT 'inbox'
        );`,
      `CREATE INDEX IF NOT EXISTS idx_player_mail_to ON players.player_mail(to_player_id, folder);`,
      `CREATE TABLE IF NOT EXISTS world.world_board (
          board_id TEXT NOT NULL,
          region_id TEXT,
          name TEXT NOT NULL,
          description TEXT,
          max_posts INT NOT NULL DEFAULT 200,
          read_perm INT NOT NULL DEFAULT 0,
          write_perm INT NOT NULL DEFAULT 10,
          PRIMARY KEY (board_id)
        );`,
      `CREATE TABLE IF NOT EXISTS players.player_board_post (
          post_id BIGSERIAL PRIMARY KEY,
          board_id TEXT NOT NULL,
          author_id INT NOT NULL,
          author_name TEXT NOT NULL,
          subject TEXT NOT NULL,
          body TEXT NOT NULL,
          posted_at BIGINT NOT NULL
        );`,
    ],
  },
  {
    version: 23,
    name: 'create_classes_and_races',
    sql: [
      `CREATE TABLE IF NOT EXISTS world.world_classes (
          class_id TEXT NOT NULL,
          name TEXT NOT NULL,
          description TEXT,
          primary_stat TEXT,
          hp_per_level INT NOT NULL DEFAULT 10,
          mp_per_level INT NOT NULL DEFAULT 5,
          PRIMARY KEY (class_id)
        );`,
      `CREATE TABLE IF NOT EXISTS world.world_races (
          race_id TEXT NOT NULL,
          name TEXT NOT NULL,
          description TEXT,
          str_bonus INT NOT NULL DEFAULT 0,
          dex_bonus INT NOT NULL DEFAULT 0,
          int_bonus INT NOT NULL DEFAULT 0,
          con_bonus INT NOT NULL DEFAULT 0,
          wis_bonus INT NOT NULL DEFAULT 0,
          cha_bonus INT NOT NULL DEFAULT 0,
          PRIMARY KEY (race_id)
        );`,
      "ALTER TABLE players.player_players ADD COLUMN IF NOT EXISTS class_id TEXT;",
      "ALTER TABLE players.player_players ADD COLUMN IF NOT EXISTS race_id TEXT;",
      "ALTER TABLE players.player_players ADD COLUMN IF NOT EXISTS level INT NOT NULL DEFAULT 1;",
    ],
  },
  {
    version: 24,
    name: 'create_zones',
    sql: [
      `CREATE TABLE IF NOT EXISTS world.world_zones (
          region_id TEXT NOT NULL,
          zone_id INTEGER NOT NULL,
          name TEXT NOT NULL,
          description TEXT,
          rules_json TEXT,
          zone_script_ref TEXT,
          is_active BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          PRIMARY KEY (region_id, zone_id)
        );`,
      "ALTER TABLE world.world_rooms ADD COLUMN IF NOT EXISTS zone_id INTEGER NOT NULL DEFAULT 0;",
      "CREATE INDEX IF NOT EXISTS world_rooms_region_zone_idx ON world.world_rooms (region_id, zone_id);",
    ],
  },
  {
    version: 25,
    name: 'fix_room_exits_and_spawns_identity',
    sql: [
      `DO $$
       BEGIN
         IF NOT EXISTS (
           SELECT 1 FROM pg_tables WHERE schemaname = 'world' AND tablename = 'world_room_exits'
         ) THEN
           CREATE TABLE world.world_room_exits (
             id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             region_id     TEXT NOT NULL,
             from_room_id  INTEGER NOT NULL,
             direction     TEXT NOT NULL,
             to_room_id    INTEGER NOT NULL,
             dest_x        INTEGER DEFAULT -1,
             dest_y        INTEGER DEFAULT -1,
             is_one_way    INTEGER DEFAULT 0,
             is_portal     INTEGER DEFAULT 0,
             portal_name   TEXT,
             auto_trigger  INTEGER DEFAULT 1
           );
           CREATE INDEX IF NOT EXISTS idx_world_exits_from ON world.world_room_exits(region_id, from_room_id);
         ELSE
           IF NOT EXISTS (
             SELECT 1 FROM pg_attribute
              WHERE attrelid = 'world.world_room_exits'::regclass
                AND attname = 'id'
                AND attidentity != ''
           ) THEN
             ALTER TABLE world.world_room_exits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
           END IF;
         END IF;
       END
       $$;`,
      `DO $$
       BEGIN
         IF NOT EXISTS (
           SELECT 1 FROM pg_tables WHERE schemaname = 'world' AND tablename = 'world_room_spawns'
         ) THEN
           CREATE TABLE world.world_room_spawns (
             id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             region_id     TEXT NOT NULL,
             room_id       INTEGER NOT NULL,
             x             INTEGER NOT NULL,
             y             INTEGER NOT NULL,
             type          TEXT NOT NULL,
             template_id   TEXT NOT NULL,
             respawn_time  DOUBLE PRECISION DEFAULT 30.0,
             is_respawning INTEGER DEFAULT 1,
             override_json TEXT
           );
           CREATE INDEX IF NOT EXISTS idx_world_spawns_room ON world.world_room_spawns(region_id, room_id);
         ELSE
           IF NOT EXISTS (
             SELECT 1 FROM pg_attribute
              WHERE attrelid = 'world.world_room_spawns'::regclass
                AND attname = 'id'
                AND attidentity != ''
           ) THEN
             ALTER TABLE world.world_room_spawns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
           END IF;
         END IF;
       END
       $$;`,
    ],
  },
]

export function ensureSchemas(): Promise<void> {
  return (async () => {
    const pool = getPool()
    await pool.query(`CREATE SCHEMA IF NOT EXISTS world`)
    await pool.query(`CREATE SCHEMA IF NOT EXISTS players`)
    await pool.query(`CREATE SCHEMA IF NOT EXISTS _meta`)
  })()
}

async function ensureMigrationsTable(): Promise<void> {
  const pool = getPool()
  await pool.query(
    `CREATE TABLE IF NOT EXISTS _meta._migrations (
      version INTEGER PRIMARY KEY,
      name TEXT NOT NULL,
      applied_at BIGINT NOT NULL,
      note TEXT
    )`,
  )
}

async function tableExists(schema: string, table: string): Promise<boolean> {
  const r = await getPool().query<{ exists: boolean }>(
    `SELECT EXISTS (
       SELECT 1 FROM information_schema.tables
       WHERE table_schema = $1 AND table_name = $2
     ) AS exists`,
    [schema, table],
  )
  return !!r.rows[0]?.exists
}

async function columnExists(schema: string, table: string, column: string): Promise<boolean> {
  const r = await getPool().query<{ exists: boolean }>(
    `SELECT EXISTS (
       SELECT 1 FROM information_schema.columns
       WHERE table_schema = $1 AND table_name = $2 AND column_name = $3
     ) AS exists`,
    [schema, table, column],
  )
  return !!r.rows[0]?.exists
}

interface MigrationSignature {
  table?: { schema: string; table: string }
  column?: { schema: string; table: string; column: string }
  columnIdentity?: { schema: string; table: string; column: string }
  revertColumn?: { schema: string; table: string; column: string }
  alwaysApplied?: boolean
}

const SIGNATURES: Record<number, MigrationSignature> = {
  1:  { column: { schema: 'world',    table: 'world_mobs',    column: 'dialogue_root' } },
  2:  { table:  { schema: 'world',    table: 'world_quests' } },
  3:  { table:  { schema: 'world',    table: 'world_quest_objectives' } },
  4:  { table:  { schema: 'world',    table: 'world_quest_rewards' } },
  5:  { column: { schema: 'world',    table: 'world_worlds',  column: 'symbol_width' } },
  6:  { column: { schema: 'world',    table: 'world_regions', column: 'floor_settings_deprecated_at' } },
  7:  { alwaysApplied: true },
  8:  { column: { schema: 'world',    table: 'world_terrains', column: 'pattern' } },
  9:  { alwaysApplied: true },
  10: { column: { schema: 'world',    table: 'world_terrains', column: 'pattern' }, revertColumn: { schema: 'world', table: 'world_terrains', column: 'pattern' } },
  11: { column: { schema: 'world',    table: 'world_regions', column: 'region_kind' } },
  12: { table:  { schema: 'world',    table: 'world_recipes' } },
  13: { table:  { schema: 'players',  table: 'player_known_recipes' } },
  14: { column: { schema: 'world',    table: 'world_skills',  column: 'xp_curve' } },
  15: { column: { schema: 'world',    table: 'world_interactables', column: 'station_type' } },
  16: { alwaysApplied: true },
  17: { column: { schema: 'world',    table: 'world_regions', column: 'floor_palette_json' } },
  18: { column: { schema: 'world',    table: 'world_regions', column: 'region_kind' }, revertColumn: { schema: 'world', table: 'world_regions', column: 'region_kind' } },
  19: { column: { schema: 'world',    table: 'world_rooms',   column: 'light' } },
  20: { table:  { schema: 'world',    table: 'world_factions' } },
  21: { column: { schema: 'players',  table: 'player_players', column: 'gold' } },
  22: { table:  { schema: 'players',  table: 'player_mail' } },
  23: { column: { schema: 'players',  table: 'player_players', column: 'level' } },
  24: { table:  { schema: 'world',    table: 'world_zones' } },
  25: { columnIdentity: { schema: 'world', table: 'world_room_exits', column: 'id' } },
}

async function isEffectPresent(m: Migration): Promise<boolean> {
  const sig = SIGNATURES[m.version]
  if (!sig) {
    const m0010Noop = m.version === 9
    return m0010Noop
  }
  if (sig.alwaysApplied) return true
  if (sig.column) {
    const present = await columnExists(sig.column.schema, sig.column.table, sig.column.column)
    if (sig.revertColumn) {
      return !present
    }
    return present
  }
  if (sig.columnIdentity) {
    const r = await getPool().query<{ attidentity: string }>(
      `SELECT COALESCE(a.attidentity, '') AS attidentity
         FROM pg_attribute a
         JOIN pg_class c ON c.oid = a.attrelid
         JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = $1 AND c.relname = $2 AND a.attname = $3`,
      [sig.columnIdentity.schema, sig.columnIdentity.table, sig.columnIdentity.column],
    )
    return r.rows.length > 0 && r.rows[0]!.attidentity !== ''
  }
  if (sig.table) {
    return await tableExists(sig.table.schema, sig.table.table)
  }
  return false
}

export async function synthesizeAppliedMigrations(): Promise<{ synthesized: MigrationRecord[]; skipped: number[] }> {
  await ensureSchemas()
  await ensureMigrationsTable()
  const applied = new Set((await getAppliedMigrations()).map((m) => m.version))
  const pool = getPool()
  const client = await pool.connect()
  const synthesized: MigrationRecord[] = []
  const skipped: number[] = []
  try {
    await client.query('begin')
    for (const m of MIGRATIONS) {
      if (applied.has(m.version)) {
        skipped.push(m.version)
        continue
      }
      const present = await isEffectPresent(m)
      if (!present) continue
      await client.query(
        `insert into _meta._migrations (version, name, applied_at, note) values ($1, $2, $3, $4)
         on conflict (version) do nothing`,
        [m.version, m.name, Date.now(), 'synthesized from existing schema'],
      )
      synthesized.push({ version: m.version, name: m.name, applied_at: Date.now(), note: 'synthesized from existing schema' })
    }
    await client.query('commit')
  } catch (e) {
    await client.query('rollback').catch(() => {})
    throw e
  } finally {
    client.release()
  }
  return { synthesized, skipped }
}

export async function getAppliedMigrations(): Promise<MigrationRecord[]> {
  await ensureSchemas()
  await ensureMigrationsTable()
  const res = await getPool().query<MigrationRecord>(
    `select version, name, applied_at, note from _meta._migrations order by version asc`,
  )
  return res.rows
}

export async function getPendingMigrations(): Promise<Migration[]> {
  const applied = new Set((await getAppliedMigrations()).map((m) => m.version))
  return MIGRATIONS.filter((m) => !applied.has(m.version)).sort(
    (a, b) => a.version - b.version,
  )
}

function snapshotsDir(): string {
  const root = process.env.MUD_SNAPSHOTS_DIR
    ?? resolve(process.cwd(), '..', 'ModularMudServer', 'mud.db.snapshots')
  if (!existsSync(root)) mkdirSync(root, { recursive: true })
  return root
}

async function backupDatabase(): Promise<string> {
  const url = process.env.MUD_DATABASE_URL
  if (!url) throw new Error('MUD_DATABASE_URL is required for backup')
  const dir = snapshotsDir()
  const ts = new Date().toISOString().replace(/[:.]/g, '-')
  const file = resolve(dir, `mud.snap.${ts}.sql`)
  await pExec('pg_dump', [
    '--no-owner',
    '--no-privileges',
    '--clean',
    '--if-exists',
    '--file', file,
    url,
  ], { timeout: 60_000 })
  return file
}

export interface RunResult {
  backup: string | null
  results: Array<{
    version: number
    name: string
    ok: boolean
    error?: string
  }>
}

export async function runPendingMigrations(options: { backup: boolean; skipVersions?: number[] }): Promise<RunResult> {
  await ensureSchemas()
  const applied = new Set((await getAppliedMigrations()).map((m) => m.version))
  const skip = new Set(options.skipVersions ?? [])
  const pending = MIGRATIONS
    .filter((m) => !applied.has(m.version) && !skip.has(m.version))
    .sort((a, b) => a.version - b.version)

  if (pending.length === 0) {
    return { backup: null, results: [] }
  }

  const backup = options.backup ? await backupDatabase() : null

  const pool = getPool()
  const client = await pool.connect()
  const results: RunResult['results'] = []
  try {
    await client.query('begin')
    for (const m of pending) {
      try {
        for (const stmt of m.sql) {
          await client.query(rewriteSql(stmt))
        }
        await client.query(
          `insert into _meta._migrations (version, name, applied_at, note) values ($1, $2, $3, $4)`,
          [m.version, m.name, Date.now(), null],
        )
        results.push({ version: m.version, name: m.name, ok: true })
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : String(e)
        results.push({ version: m.version, name: m.name, ok: false, error: msg })
        break
      }
    }
    await client.query('commit')
  } catch (e) {
    await client.query('rollback').catch(() => {})
    throw e
  } finally {
    client.release()
  }

  return { backup, results }
}

export async function listBackups(): Promise<Array<{ path: string; mtime: number; size: number }>> {
  const dir = snapshotsDir()
  if (!existsSync(dir)) return []
  const entries = await Promise.resolve(readdirSync(dir))
  return entries
    .filter((f) => f.startsWith('mud.snap.') && f.endsWith('.sql'))
    .map((f) => {
      const full = resolve(dir, f)
      const st = statSync(full)
      return { path: full, mtime: st.mtimeMs, size: st.size }
    })
    .sort((a, b) => b.mtime - a.mtime)
}

export async function runPgDump(target: string): Promise<void> {
  const url = process.env.MUD_DATABASE_URL
  if (!url) throw new Error('MUD_DATABASE_URL is required')
  await pExec('pg_dump', [
    '--no-owner',
    '--no-privileges',
    '--clean',
    '--if-exists',
    '--file', target,
    url,
  ], { timeout: 60_000 })
}

export async function restoreFromSql(file: string): Promise<void> {
  const url = process.env.MUD_DATABASE_URL
  if (!url) throw new Error('MUD_DATABASE_URL is required for restore')
  await pExec('psql', [
    '--dbname', url,
    '--single-transaction',
    '--variable', 'ON_ERROR_STOP=1',
    '--file', file,
  ], { timeout: 120_000 })
}

export { qualifiedTable }
