import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { copyFileSync, existsSync, mkdirSync, readdirSync, statSync } from 'node:fs'
import { resolve } from 'node:path'
import { getPool } from './db'

const pExec = promisify(execFile)

export interface Migration {
  version: number
  name: string
  sql: string[]
}

export interface MigrationRecord {
  version: number
  name: string
  applied_at: number
  note: string | null
}

function qualifiedTable(name: string): string {
  if (name.startsWith('players.')) {
    const t = name.slice('players.'.length)
    return `players.${t}`
  }
  if (name.startsWith('_meta.')) {
    const t = name.slice('_meta.'.length)
    return `_meta.${t}`
  }
  if (name === '_migrations') return '_meta._migrations'
  return `world.${name}`
}

function rewriteSql(sql: string): string {
  return sql
    .replace(/\b_migrations\b/g, '_meta._migrations')
    .replace(/\bplayers\.player_/g, 'players.player_')
    .replace(/\bplayers\._/g, 'players._')
    .replace(/\bCREATE TABLE IF NOT EXISTS\s+world_/g, 'CREATE TABLE IF NOT EXISTS world.world_')
    .replace(/\bCREATE TABLE IF NOT EXISTS\s+player_/g, 'CREATE TABLE IF NOT EXISTS players.player_')
    .replace(/\bALTER TABLE\s+world_/g, 'ALTER TABLE world.world_')
    .replace(/\bALTER TABLE\s+player_/g, 'ALTER TABLE players.player_')
    .replace(/\bUPDATE\s+world_/g, 'UPDATE world.world_')
    .replace(/\bUPDATE\s+player_/g, 'UPDATE players.player_')
    .replace(/\bDROP COLUMN\s+pattern\b/g, 'DROP COLUMN pattern')
    .replace(/PRIMARY KEY AUTOINCREMENT/g, 'GENERATED BY DEFAULT AS IDENTITY')
    .replace(/AUTOINCREMENT/g, 'GENERATED BY DEFAULT AS IDENTITY')
}

const MIGRATIONS: Migration[] = [
  {
    version: 1,
    name: 'add_dialogue_root_to_world_mobs',
    sql: ['ALTER TABLE world.world_mobs ADD COLUMN dialogue_root TEXT;'],
  },
  {
    version: 2,
    name: 'create_world_quests',
    sql: [
      `CREATE TABLE IF NOT EXISTS world.world_quests (
        world_id TEXT NOT NULL,
        quest_id TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        script_ref TEXT,
        PRIMARY KEY (world_id, quest_id)
      );`,
    ],
  },
  {
    version: 3,
    name: 'create_world_quest_objectives',
    sql: [
      `CREATE TABLE IF NOT EXISTS world.world_quest_objectives (
        world_id TEXT NOT NULL,
        quest_id TEXT NOT NULL,
        ordinal INTEGER NOT NULL,
        kind TEXT NOT NULL,
        target TEXT,
        count INTEGER DEFAULT 1,
        PRIMARY KEY (world_id, quest_id, ordinal)
      );`,
    ],
  },
  {
    version: 4,
    name: 'create_world_quest_rewards',
    sql: [
      `CREATE TABLE IF NOT EXISTS world.world_quest_rewards (
        world_id TEXT NOT NULL,
        quest_id TEXT NOT NULL,
        ordinal INTEGER NOT NULL,
        kind TEXT NOT NULL,
        payload_json TEXT,
        PRIMARY KEY (world_id, quest_id, ordinal)
      );`,
    ],
  },
  {
    version: 5,
    name: 'add_symbol_width_to_world_worlds',
    sql: ['ALTER TABLE world.world_worlds ADD COLUMN symbol_width INTEGER DEFAULT 1;'],
  },
  {
    version: 6,
    name: 'migrate_floor_settings_overrides',
    sql: [
      "ALTER TABLE world.world_regions ADD COLUMN floor_settings_deprecated_at INTEGER;",
    ],
  },
  {
    version: 7,
    name: 'create_migrations_table_marker',
    sql: [
      `CREATE TABLE IF NOT EXISTS _meta._migrations (
        version INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        applied_at BIGINT NOT NULL,
        note TEXT
      );`,
    ],
  },
  {
    version: 8,
    name: 'add_pattern_to_world_terrains',
    sql: [
      "ALTER TABLE world.world_terrains ADD COLUMN pattern TEXT DEFAULT 'none';",
    ],
  },
  {
    version: 9,
    name: 'auto_assign_patterns_to_default_tiles',
    sql: [
      "UPDATE world.world_terrains SET pattern = 'hatch'   WHERE symbol = 'x';",
      "UPDATE world.world_terrains SET pattern = 'dots'    WHERE symbol = '~';",
      "UPDATE world.world_terrains SET pattern = 'stripes' WHERE symbol = 'T';",
      "UPDATE world.world_terrains SET pattern = 'none'    WHERE symbol = '.';",
    ],
  },
  {
    version: 10,
    name: 'drop_pattern_column_from_world_terrains',
    sql: [
      'ALTER TABLE world.world_terrains DROP COLUMN pattern;',
    ],
  },
  {
    version: 11,
    name: 'add_region_metadata',
    sql: [
      "ALTER TABLE world.world_regions ADD COLUMN region_kind TEXT DEFAULT 'static';",
      'ALTER TABLE world.world_regions ADD COLUMN generator_script TEXT;',
      'ALTER TABLE world.world_regions ADD COLUMN template_config_json TEXT;',
      'ALTER TABLE world.world_regions ADD COLUMN tutorial_steps_json TEXT;',
    ],
  },
  {
    version: 12,
    name: 'create_world_recipes',
    sql: [
      `CREATE TABLE IF NOT EXISTS world.world_recipes (
        world_id TEXT NOT NULL,
        recipe_id TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        skill_id TEXT,
        required_skill_level INTEGER DEFAULT 0,
        station_type TEXT,
        outputs_json TEXT,
        inputs_json TEXT,
        craft_time_seconds REAL DEFAULT 3.0,
        experience_gain INTEGER DEFAULT 0,
        script_ref TEXT,
        is_auto_learned INTEGER DEFAULT 1,
        PRIMARY KEY (world_id, recipe_id)
      );`,
    ],
  },
  {
    version: 13,
    name: 'create_player_known_recipes',
    sql: [
      `CREATE TABLE IF NOT EXISTS players.player_known_recipes (
        uid INTEGER NOT NULL,
        world_id TEXT NOT NULL,
        recipe_id TEXT NOT NULL,
        learned_at BIGINT NOT NULL,
        PRIMARY KEY (uid, world_id, recipe_id)
      );`,
    ],
  },
  {
    version: 14,
    name: 'add_xp_curve_to_world_skills',
    sql: [
      "ALTER TABLE world.world_skills ADD COLUMN xp_curve TEXT DEFAULT 'linear';",
      'ALTER TABLE world.world_skills ADD COLUMN xp_curve_params TEXT;',
    ],
  },
  {
    version: 15,
    name: 'add_station_type_to_world_interactables',
    sql: [
      'ALTER TABLE world.world_interactables ADD COLUMN station_type TEXT;',
    ],
  },
]

export function ensureSchemas(): Promise<void> {
  return (async () => {
    const pool = getPool()
    await pool.query(`CREATE SCHEMA IF NOT EXISTS world`)
    await pool.query(`CREATE SCHEMA IF NOT EXISTS players`)
    await pool.query(`CREATE SCHEMA IF NOT EXISTS _meta`)
  })()
}

async function ensureMigrationsTable(): Promise<void> {
  const pool = getPool()
  await pool.query(
    `CREATE TABLE IF NOT EXISTS _meta._migrations (
      version INTEGER PRIMARY KEY,
      name TEXT NOT NULL,
      applied_at BIGINT NOT NULL,
      note TEXT
    )`,
  )
}

export async function getAppliedMigrations(): Promise<MigrationRecord[]> {
  await ensureSchemas()
  await ensureMigrationsTable()
  const res = await getPool().query<MigrationRecord>(
    `select version, name, applied_at, note from _meta._migrations order by version asc`,
  )
  return res.rows
}

export async function getPendingMigrations(): Promise<Migration[]> {
  const applied = new Set((await getAppliedMigrations()).map((m) => m.version))
  return MIGRATIONS.filter((m) => !applied.has(m.version)).sort(
    (a, b) => a.version - b.version,
  )
}

function snapshotsDir(): string {
  const root = process.env.MUD_SNAPSHOTS_DIR
    ?? resolve(process.cwd(), '..', 'ModularMudServer', 'mud.db.snapshots')
  if (!existsSync(root)) mkdirSync(root, { recursive: true })
  return root
}

async function backupDatabase(): Promise<string> {
  const url = process.env.MUD_DATABASE_URL
  if (!url) throw new Error('MUD_DATABASE_URL is required for backup')
  const dir = snapshotsDir()
  const ts = new Date().toISOString().replace(/[:.]/g, '-')
  const file = resolve(dir, `mud.snap.${ts}.sql`)
  await pExec('pg_dump', [
    '--no-owner',
    '--no-privileges',
    '--clean',
    '--if-exists',
    '--file', file,
    url,
  ], { timeout: 60_000 })
  return file
}

export interface RunResult {
  backup: string | null
  results: Array<{
    version: number
    name: string
    ok: boolean
    error?: string
  }>
}

export async function runPendingMigrations(options: { backup: boolean; skipVersions?: number[] }): Promise<RunResult> {
  await ensureSchemas()
  const applied = new Set((await getAppliedMigrations()).map((m) => m.version))
  const skip = new Set(options.skipVersions ?? [])
  const pending = MIGRATIONS
    .filter((m) => !applied.has(m.version) && !skip.has(m.version))
    .sort((a, b) => a.version - b.version)

  if (pending.length === 0) {
    return { backup: null, results: [] }
  }

  const backup = options.backup ? await backupDatabase() : null

  const pool = getPool()
  const client = await pool.connect()
  const results: RunResult['results'] = []
  try {
    await client.query('begin')
    for (const m of pending) {
      try {
        for (const stmt of m.sql) {
          await client.query(rewriteSql(stmt))
        }
        await client.query(
          `insert into _meta._migrations (version, name, applied_at, note) values ($1, $2, $3, $4)`,
          [m.version, m.name, Date.now(), null],
        )
        results.push({ version: m.version, name: m.name, ok: true })
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : String(e)
        results.push({ version: m.version, name: m.name, ok: false, error: msg })
        break
      }
    }
    await client.query('commit')
  } catch (e) {
    await client.query('rollback').catch(() => {})
    throw e
  } finally {
    client.release()
  }

  return { backup, results }
}

export async function listBackups(): Promise<Array<{ path: string; mtime: number; size: number }>> {
  const dir = snapshotsDir()
  if (!existsSync(dir)) return []
  const entries = await Promise.resolve(readdirSync(dir))
  return entries
    .filter((f) => f.startsWith('mud.snap.') && f.endsWith('.sql'))
    .map((f) => {
      const full = resolve(dir, f)
      const st = statSync(full)
      return { path: full, mtime: st.mtimeMs, size: st.size }
    })
    .sort((a, b) => b.mtime - a.mtime)
}

export async function runPgDump(target: string): Promise<void> {
  const url = process.env.MUD_DATABASE_URL
  if (!url) throw new Error('MUD_DATABASE_URL is required')
  await pExec('pg_dump', [
    '--no-owner',
    '--no-privileges',
    '--clean',
    '--if-exists',
    '--file', target,
    url,
  ], { timeout: 60_000 })
}

export async function restoreFromSql(file: string): Promise<void> {
  const url = process.env.MUD_DATABASE_URL
  if (!url) throw new Error('MUD_DATABASE_URL is required for restore')
  await pExec('psql', [
    '--dbname', url,
    '--single-transaction',
    '--variable', 'ON_ERROR_STOP=1',
    '--file', file,
  ], { timeout: 120_000 })
}

export { qualifiedTable }
